version: "3.7"
services:
  db:
    image: postgres:13.4-alpine
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db/data/:/docker-entrypoint-initdb.d
  rest-api:
    image: fiber:local
    container_name: rest-api
    build:
      context: .
      dockerfile: services/rest-api/deployments/Dockerfile
      target: local
      args:
        SERVICE_NAME: rest-api
    env_file: .dev.env
    depends_on:
      - db
    ports:
      - '8080:8080'
    volumes:
      - ./rest-api:/perch/rest-api
volumes:
  postgres-data: